services:
  # Frontend Service
  - type: web
    name: resume-analyzer-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://resume-analyzer-api.onrender.com

  # Backend Service
  - type: web
    name: resume-analyzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: api
